name: lego_app
description: "A cross-platform LEGO set rebuilding application."
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.10.3

dependencies:
  bitsdojo_window: ^0.1.6
  cached_network_image: ^3.4.1
  cached_network_image_web: ^1.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1
  hooks_riverpod: ^3.0.3
  http: ^1.6.0
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.0
  url_launcher: ^6.3.2
  yaru: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
